colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
disableTextInHeader = true
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = ""

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = "7"
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = "Librar-Logo-Domain.png"

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = ""
showBreadcrumbs = ""
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = false
invertPagination = ""
showReadingTime = false
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = ""
showWordCount = false
showZenMode = ""
heroStyle = "background"
showRelatedContent = true
relatedContentLimit = "3"
sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram" ]

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = ""
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = ""
heroStyle = ""

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false
heroStyle = "basic"

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
